apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-cleaner
  namespace: k8s-lifecycle-prod
spec:
  schedule: "*/1 * * * *"
  # Кнопки управления историей:
  successfulJobsHistoryLimit: 1   # Хранить только 1 последний успешный под
  failedJobsHistoryLimit: 1       # Хранить только 1 последний упавший под
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleaner
            image: busybox
            command: ["echo", "Логи очищены."]
          restartPolicy: OnFailure
