apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-db-pv-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-storage
  local:
    path: /mnt/data             # Путь на диске вашего сервера/ноутбука
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube            # Имя вашего узла (уточните через kubectl get nodes)
