apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: k8s-lifecycle-prod
spec:
  clusterIP: None                # Это делает сервис Headless
  selector:
    app: database                # Должно совпадать с меткой в StatefulSet
  ports:
  - port: 5432                   # Порт БД (например, Postgres)
    name: db-port
