apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: k8s-lifecycle-prod
spec:
  limits:
  - default:                # Лимит по умолчанию (Limit)
      cpu: 500m
      memory: 512Mi
    defaultRequest:         # Запрос по умолчанию (Request)
      cpu: 200m
      memory: 256Mi
    type: Container
